
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: richie
    url: jdbc:postgresql://kexogg.ru:52345/
    password: DrMKKpMpAMRT9qfvaX2GVDZ76Svi3HPoynqnbME3WAxZdoSD9XhZCJZCd8gpoCnK
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

server:
  port: '55555'